def add(x,y):
    return x+y
def sub(x,y):
    return x-y
def multiply(x,y):
    return x*y
def divide(x,y):
    return x/y
def greet():
    print("Hello Everyone")
def greeting(name='Pranjal'):
    print(f"Hello {name}")